CREATE TABLE BUILDING_INFO 
(BLD_ID CHAR(4),
BLD_NAME VARCHAR2(32) PRIMARY KEY,
NO_VERTICES NUMBER, 
BLD_GEOM MDSYS.SDO_GEOMETRY
);

CREATE TABLE FIREHYDRANTS_INFO
(FIREHYD_ID CHAR(4) PRIMARY KEY,
FH_GEOM MDSYS.SDO_GEOMETRY);

CREATE TABLE BLD_ON_FIRE
(BLD_NAME VARCHAR2(32),
FOREIGN KEY (BLD_NAME) REFERENCES BUILDING_INFO(BLD_NAME)
);

INSERT INTO USER_SDO_GEOM_METADATA
(TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES
('BUILDING_INFO','BLD_GEOM',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('X',0, 830, 0.005),MDSYS.SDO_DIM_ELEMENT('Y',0, 600, 0.005)
),
NULL
);

INSERT INTO USER_SDO_GEOM_METADATA
(TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES
('FIREHYDRANTS_INFO','FH_GEOM',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('X',0, 830, 0.005),MDSYS.SDO_DIM_ELEMENT('Y',0, 600, 0.005)
),
NULL
);

CREATE INDEX BLD_INDEX ON BUILDING_INFO(BLD_GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX FH_INDEX ON FIREHYDRANTS_INFO(FH_GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
